#!/usr/bin/env ruby
#############################################################
# thin_memory - A munin plugin to monitor memory size of
#                  each individual thin process
#
# For Linux ONLY !
# DOES NOT WORK on OSX, Solaris or BSD.
# only linux, because this script relies on proc filesystem
#
#############################################################
#
# Based on original code and ideas from:
# thin_process_memory - A munin plugin to monitor memory size of 
#                          each individual thin process
# Copyright (C) 2007 Ben VandenBos and Avvo, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Original Author: Ben VandenBos
# Contributors: Adam Jacob (<adam@hjksolutions.com>)
#               Ryan Woodrum 
#               Matthias Marschall (mm@agileweboperations.com)
#
# Thanks Matthias to help improve this code and made much faster
#
#%# family=auto
#%# capabilities=autoconf

module Munin
  class ThinProcessMemory
    
    def run
      pids = get_pids()
      port_list = Hash.new
      pids.sort.each do |pid, port|
        rss = (pid_rss(pid).to_i)/1024
        puts "thin_#{port}.value #{rss}"
      end
    end
    
    def pid_rss(pid)
      res = `grep "VmRSS" /proc/#{pid}/status`.split[1]
      if res.match("cannot access")
        return nil
      else
        return res
      end
    end
    
    def get_pids
      pids_ports = []
      Dir["/var/www/apps/*/shared/pids/thin*.pid"].each do |pid_file|
        pid = `cat #{pid_file}`
        port = pid_file[/\d\d\d\d/]
        pids_ports << [pid,port]
      end
      pids_ports
    end

    def autoconf
      get_pids().length > 0
    end
    
  end
end

mpm = Munin::ThinProcessMemory.new

case ARGV[0]
when "config"
  puts "graph_title Thin Memory"
  puts "graph_vlabel RSS (MB)"
  puts "graph_category Thin"
  puts "graph_args --base 1024 -l 0"
  puts "graph_scale yes"
  puts "graph_info Tracks the size of individual thin processes"
  mpm.get_pids.sort.each do |pid,port|
    puts "thin_#{port}.label thin_#{port}"
    puts "thin_#{port}.info Process memory"
    puts "thin_#{port}.type GAUGE"
    puts "thin_#{port}.min 0"
  end
when "autoconf"
  if mpm.autoconf
    puts "yes"
    exit 0
  end
  puts "no"
  exit 1
else
  mpm.run
end


